export enum StudioTypes {
  STUDIO_LIST_SET = "STUDIO_LIST_SET",
  STUDIO_LIST_ADD = "STUDIO_LIST_ADD",
  STUDIO_POPULATED_STATUS_SET = "STUDIO_POPULATED_STATUS_SET",
  STUDIO_RESET = "STUDIO_RESET",
}

export default StudioTypes;
