export enum StudioTypes {
  STUDIO_FETCHING = "STUDIO_FETCHING",
  STUDIO_FETCH_SUCCESS = "STUDIO_FETCH_SUCCESS",
  STUDIO_FETCH_REJECT = "STUDIO_FETCH_REJECT",
  STUDIO_APPEND = "STUDIO_APPEND",
  STUDIO_SET_HOVERED = "STUDIO_SET_HOVERED",
  STUDIO_SET_OPENED = "STUDIO_SET_OPENED",
}

export default StudioTypes;
