export enum StudioTypes {
  STUDIO_LIST_SET = "STUDIO_LIST_SET",
  STUDIO_LIST_ADD = "STUDIO_LIST_ADD",
  STUDIO_POPULATED_STATUS_SET = "STUDIO_POPULATED_STATUS_SET",
  STUDIO_RESET = "STUDIO_RESET",
  STUDIO_SET_HOVERED_STUDIO = "STUDIO_SET_HOVERED_STUDIO",
  STUDIO_SET_OPENED_STUDIO = "STUDIO_SET_OPENED_STUDIO",
}

export default StudioTypes;
