export enum StudioTypes {
    STUDIOS_FETCHING = "STUDIOS_FETCHING",
    STUDIOS_FETCH_SUCCESS = "STUDIOS_FETCH_SUCCESS",
    STUDIOS_FETCH_REJECT = "STUDIOS_FETCH_REJECT",
    STUDIOS_SET_HOVERED = "STUDIOS_SET_HOVERED",
    STUDIOS_SET_OPENED = "STUDIOS_SET_OPENED",
    STUDIOS_SET_FILTERED_AMOUNT = "STUDIOS_SET_FILTERED_AMOUNT",
}

export default StudioTypes;
