export enum StudioTypes {
    UNITS_FETCHING = "UNITS_FETCHING",
    UNITS_FETCH_SUCCESS = "UNITS_FETCH_SUCCESS",
    UNITS_FETCH_REJECT = "UNITS_FETCH_REJECT",
    UNITS_SET_HOVERED = "UNITS_SET_HOVERED",
    UNITS_SET_OPENED = "UNITS_SET_OPENED",
    UNITS_SET_FILTERED_AMOUNT = "UNITS_SET_FILTERED_AMOUNT",
}

export default StudioTypes;
