export enum MessageTypes {
  MESSAGE_SENDING = "MESSAGE_SENDING",
  MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS",
  MESSAGE_SEND_REJECT = "MESSAGE_SEND_REJECT",
  MESSAGE_SET_IDLE = "MESSAGE_SET_IDLE",
}

export default MessageTypes;
