export enum MessageTypes {
  MESSAGE_SENDING = "MESSAGE_SENDING",
  MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS",
  MESSAGE_SEND_REJECT = "MESSAGE_SEND_REJECT",
  MESSAGE_RELOAD = "MESSAGE_RELOAD",
}

export default MessageTypes;
